### ISSUE TITLE
NER模型训练完成后，通过run_test.py调用正常，但是通过run_deploy.py调用出错

### ISSUE THREAD

**Issue by siyu828** [liushaoweihua/keras-bert-ner#1]
问题如题，模型的配置参数完全一样，错误信息如下：
[2019-11-04 16:44:55,208] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Python37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Program Files\Python37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:/workspace/keras-bert-ner/examples/deploy_example/run_deploy.py", line 86, in callback
    res = parse(text)
  File "F:/workspace/keras-bert-ner/examples/deploy_example/run_deploy.py", line 57, in parse
    decode_res = viterbi_decoder.decode([tokens, segs])
  File "F:\workspace\keras-bert-ner\keras_bert_ner\decode\viterbi.py", line 42, in decode
    pred_res = np.array(self.model.predict(data))
  File "D:\Program Files\Python37\lib\site-packages\keras\engine\training.py", line 1456, in predict
    self._make_predict_function()
  File "D:\Program Files\Python37\lib\site-packages\keras\engine\training.py", line 378, in _make_predict_function
    **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\keras\backend\tensorflow_backend.py", line 3009, in function
    **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3678, in function
    return GraphExecutionFunction(inputs, outputs, updates=updates, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3330, in __init__
    with ops.control_dependencies([self.outputs[0]]):
  File "D:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5254, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "D:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 4688, in control_dependencies
    c = self.as_graph_element(c)
  File "D:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "D:\Program Files\Python37\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3686, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("crf_1/cond/Merge:0", shape=(?, 127, 8), dtype=float32) is not an element of this graph.
127.0.0.1 - - [04/Nov/2019 16:44:55] "GET /?s=火币网全球站自2013年成立以来,先后获得真格基金、红杉资本投资 HTTP/1.1" 500 -

测试过程：
1、启动run_deploy.py 加载模型，期间无出错信息
2、待WEB服务启动完成后，通过浏览器发送请求
3、浏览器返回500错误，后端日志如上

敢问大神们，这是什么原因呢？

**Comment by siyu828** [comment]
TF 环境：1.15.0

**Comment by siyu828** [comment]
问题已经解决，参考https://github.com/BrikerMan/Kashgari/issues/167 
需要在加载模型和预测的时候保证graph相同
