### ISSUE TITLE
ValueError: Layer weight shape (512, 128) not compatible with provided weight shape (512, 312)

### ISSUE THREAD

**Issue by chenxiangzhen** [liushaoweihua/keras-bert-ner#2]
Traceback (most recent call last):
  File "run_train.py", line 21, in <module>
    run_train()
  File "run_train.py", line 17, in run_train
    train(args=args)
  File "/home/dev/nlp/bert_ner/train.py", line 87, in train
    model = NER_Model(model_configs).build()
  File "/home/dev/nlp/bert_ner/models.py", line 37, in build
    albert = self.albert
  File "/home/dev/nlp/bert_ner/bert.py", line 469, in build_bert_model
    bert.load_weights_from_checkpoint(checkpoint_path)
  File "/home/dev/nlp/bert_ner/bert.py", line 350, in load_weights_from_checkpoint
    self.model.get_layer(layer_name).set_weights(weights)
  File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 105, in eager_fn_wrapper
    out = func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1126, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (512, 128) not compatible with provided weight shape (512, 312)Traceback (most recent call last):
  File "run_train.py", line 21, in <module>
    run_train()
  File "run_train.py", line 17, in run_train
    train(args=args)
  File "/home/dev/nlp/bert_ner/train.py", line 87, in train
    model = NER_Model(model_configs).build()
  File "/home/dev/nlp/bert_ner/models.py", line 37, in build
    albert = self.albert
  File "/home/dev/nlp/bert_ner/bert.py", line 469, in build_bert_model
    bert.load_weights_from_checkpoint(checkpoint_path)
  File "/home/dev/nlp/bert_ner/bert.py", line 350, in load_weights_from_checkpoint
    self.model.get_layer(layer_name).set_weights(weights)
  File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 105, in eager_fn_wrapper
    out = func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1126, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (512, 128) not compatible with provided weight shape (512, 312)

**Comment by liushaoweihua** [comment]
您好，这个albert是徐亮老师版本的吧，这个版本早于谷歌放出来，权重和谷歌的不一样。后面徐亮老师又训练了一个和谷歌权重一样的albert，苏神的bert4keras在0.2.3以后已经放弃支持了原徐亮老师的版本，改为支持徐亮老师训练的albert中带google字样的版本，如albert_tiny_google_zh: https://storage.googleapis.com/albert_zh/albert_tiny_zh_google.zip，albert_small_google_zh: https://storage.googleapis.com/albert_zh/albert_small_zh_google.zip。

（注：徐亮版albert的开源时间早于Google版albert，这导致早期徐亮版albert的权重与Google版的不完全一致，换言之两者不能直接相互替换。为了减少代码冗余，bert4keras的0.2.4及后续版本均只支持加载Google版以徐亮版中带Google字眼的权重。如果要加载早期版本的权重，请用0.2.3版本。）

**Comment by liushaoweihua** [comment]
您好，这个albert是徐亮老师版本的吧，这个版本早于谷歌放出来，权重和谷歌的不一样。后面徐亮老师又训练了一个和谷歌权重一样的albert，苏神的bert4keras在0.2.3以后已经放弃支持了原徐亮老师的版本，改为支持徐亮老师训练的albert中带google字样的版本，如albert_tiny_google_zh: https://storage.googleapis.com/albert_zh/albert_tiny_zh_google.zip，albert_small_google_zh: https://storage.googleapis.com/albert_zh/albert_small_zh_google.zip。

（注：徐亮版albert的开源时间早于Google版albert，这导致早期徐亮版albert的权重与Google版的不完全一致，换言之两者不能直接相互替换。为了减少代码冗余，bert4keras的0.2.4及后续版本均只支持加载Google版以徐亮版中带Google字眼的权重。如果要加载早期版本的权重，请用0.2.3版本。）

> Traceback (most recent call last):
> File "run_train.py", line 21, in
> run_train()
> File "run_train.py", line 17, in run_train
> train(args=args)
> File "/home/dev/nlp/bert_ner/train.py", line 87, in train
> model = NER_Model(model_configs).build()
> File "/home/dev/nlp/bert_ner/models.py", line 37, in build
> albert = self.albert
> File "/home/dev/nlp/bert_ner/bert.py", line 469, in build_bert_model
> bert.load_weights_from_checkpoint(checkpoint_path)
> File "/home/dev/nlp/bert_ner/bert.py", line 350, in load_weights_from_checkpoint
> self.model.get_layer(layer_name).set_weights(weights)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 105, in eager_fn_wrapper
> out = func(*args, **kwargs)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1126, in set_weights
> 'provided weight shape ' + str(w.shape))
> ValueError: Layer weight shape (512, 128) not compatible with provided weight shape (512, 312)Traceback (most recent call last):
> File "run_train.py", line 21, in
> run_train()
> File "run_train.py", line 17, in run_train
> train(args=args)
> File "/home/dev/nlp/bert_ner/train.py", line 87, in train
> model = NER_Model(model_configs).build()
> File "/home/dev/nlp/bert_ner/models.py", line 37, in build
> albert = self.albert
> File "/home/dev/nlp/bert_ner/bert.py", line 469, in build_bert_model
> bert.load_weights_from_checkpoint(checkpoint_path)
> File "/home/dev/nlp/bert_ner/bert.py", line 350, in load_weights_from_checkpoint
> self.model.get_layer(layer_name).set_weights(weights)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 105, in eager_fn_wrapper
> out = func(*args, **kwargs)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1126, in set_weights
> 'provided weight shape ' + str(w.shape))
> ValueError: Layer weight shape (512, 128) not compatible with provided weight shape (512, 312)

您好，这个albert是徐亮老师版本的吧，这个版本早于谷歌放出来，权重和谷歌的不一样。后面徐亮老师又训练了一个和谷歌权重一样的albert，苏神的bert4keras在0.2.3以后已经放弃支持了原徐亮老师的版本，改为支持徐亮老师训练的albert中带google字样的版本，如albert_tiny_google_zh: https://storage.googleapis.com/albert_zh/albert_tiny_zh_google.zip，albert_small_google_zh: https://storage.googleapis.com/albert_zh/albert_small_zh_google.zip。

（注：徐亮版albert的开源时间早于Google版albert，这导致早期徐亮版albert的权重与Google版的不完全一致，换言之两者不能直接相互替换。为了减少代码冗余，bert4keras的0.2.4及后续版本均只支持加载Google版以徐亮版中带Google字眼的权重。如果要加载早期版本的权重，请用0.2.3版本。）

**Comment by liushaoweihua** [comment]
> Traceback (most recent call last):
> File "run_train.py", line 21, in
> run_train()
> File "run_train.py", line 17, in run_train
> train(args=args)
> File "/home/dev/nlp/bert_ner/train.py", line 87, in train
> model = NER_Model(model_configs).build()
> File "/home/dev/nlp/bert_ner/models.py", line 37, in build
> albert = self.albert
> File "/home/dev/nlp/bert_ner/bert.py", line 469, in build_bert_model
> bert.load_weights_from_checkpoint(checkpoint_path)
> File "/home/dev/nlp/bert_ner/bert.py", line 350, in load_weights_from_checkpoint
> self.model.get_layer(layer_name).set_weights(weights)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 105, in eager_fn_wrapper
> out = func(*args, **kwargs)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1126, in set_weights
> 'provided weight shape ' + str(w.shape))
> ValueError: Layer weight shape (512, 128) not compatible with provided weight shape (512, 312)Traceback (most recent call last):
> File "run_train.py", line 21, in
> run_train()
> File "run_train.py", line 17, in run_train
> train(args=args)
> File "/home/dev/nlp/bert_ner/train.py", line 87, in train
> model = NER_Model(model_configs).build()
> File "/home/dev/nlp/bert_ner/models.py", line 37, in build
> albert = self.albert
> File "/home/dev/nlp/bert_ner/bert.py", line 469, in build_bert_model
> bert.load_weights_from_checkpoint(checkpoint_path)
> File "/home/dev/nlp/bert_ner/bert.py", line 350, in load_weights_from_checkpoint
> self.model.get_layer(layer_name).set_weights(weights)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 105, in eager_fn_wrapper
> out = func(*args, **kwargs)
> File "/usr/local/anaconda3/envs/tf2/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1126, in set_weights
> 'provided weight shape ' + str(w.shape))
> ValueError: Layer weight shape (512, 128) not compatible with provided weight shape (512, 312)

您好，这个albert是徐亮老师版本的吧，这个版本早于谷歌放出来，权重和谷歌的不一样。后面徐亮老师又训练了一个和谷歌权重一样的albert，苏神的bert4keras在0.2.3以后已经放弃支持了原徐亮老师的版本，改为支持徐亮老师训练的albert中带google字样的版本，如albert_tiny_google_zh: https://storage.googleapis.com/albert_zh/albert_tiny_zh_google.zip，albert_small_google_zh: https://storage.googleapis.com/albert_zh/albert_small_zh_google.zip。

（注：徐亮版albert的开源时间早于Google版albert，这导致早期徐亮版albert的权重与Google版的不完全一致，换言之两者不能直接相互替换。为了减少代码冗余，bert4keras的0.2.4及后续版本均只支持加载Google版以徐亮版中带Google字眼的权重。如果要加载早期版本的权重，请用0.2.3版本。）
