### ISSUE TITLE
albert 参数出错

### ISSUE THREAD

**Issue by shjliqian** [liushaoweihua/keras-bert-ner#5]

**Comment by shjliqian** [comment]
![image](https://user-images.githubusercontent.com/28808390/71002262-de8e7b00-2119-11ea-8f04-c85770de5882.png)
![image](https://user-images.githubusercontent.com/28808390/71002290-e9e1a680-2119-11ea-978a-967963eff0d7.png)


bert4keras参数更新了

一堆错误.....

**Comment by shjliqian** [comment]
args.albert: True
Traceback (most recent call last):
  File "train_org.py", line 25, in <module>
    run_train()
  File "train_org.py", line 21, in run_train
    train(args=args)
  File "/data/lost+found/anaconda3/envs/class_gpu/lib/python3.6/site-packages/keras_bert_ner/train/train.py", line 89, in train
    model = NER_Model(model_configs).build()
  File "/data/lost+found/anaconda3/envs/class_gpu/lib/python3.6/site-packages/keras_bert_ner/train/models.py", line 37, in build
    albert = self.albert
TypeError: build_bert_model() got an unexpected keyword argument 'albert'

bert4keras 参数更新了。。。


更新
2019.12.17: 适配华为的nezha权重，只需要在build_bert_model函数里加上model='nezha'；此外原来albert的加载方式albert=True改为model='albert'。

代码一大堆错
