### ISSUE TITLE
加载模型问题

### ISSUE THREAD

**Issue by fanfanba** [liushaoweihua/keras-bert-ner#9]
我这边使用最新的版本，加载出现问题
使用的模型是：https://storage.googleapis.com/albert_zh/albert_small_zh_google.zip
错误信息如下：
==> searching: bert/embeddings/position_embeddings, found name: bert/embeddings/position_embeddings
==> searching: bert/embeddings/token_type_embeddings, found name: bert/embeddings/token_type_embeddings
==> searching: bert/embeddings/LayerNorm/gamma, found name: bert/embeddings/LayerNorm/gamma
==> searching: bert/embeddings/LayerNorm/beta, found name: bert/embeddings/LayerNorm/beta
==> searching: bert/encoder/layer_0/attention/self/query/kernel, found name: bert/encoder/layer_0/attention/self/query/kernel
==> searching: bert/encoder/layer_0/attention/self/query/bias, found name: bert/encoder/layer_0/attention/self/query/bias
==> searching: bert/encoder/layer_0/attention/self/key/kernel, found name: bert/encoder/layer_0/attention/self/key/kernel
==> searching: bert/encoder/layer_0/attention/self/key/bias, found name: bert/encoder/layer_0/attention/self/key/bias
==> searching: bert/encoder/layer_0/attention/self/value/kernel, found name: bert/encoder/layer_0/attention/self/value/kernel
==> searching: bert/encoder/layer_0/attention/self/value/bias, found name: bert/encoder/layer_0/attention/self/value/bias
==> searching: bert/encoder/layer_0/attention/output/dense/kernel, found name: bert/encoder/layer_0/attention/output/dense/kernel
==> searching: bert/encoder/layer_0/attention/output/dense/bias, found name: bert/encoder/layer_0/attention/output/dense/bias
Traceback (most recent call last):
  File "run_train.py", line 39, in <module>
    run_train()
  File "run_train.py", line 35, in run_train
    train(args=args)
  File "../../keras_bert_ner/train.py", line 69, in train
    num_hidden_layers=args.rnn_num_hidden_layers).build()
  File "../../keras_bert_ner/utils/models.py", line 147, in __init__
    super(NerRnnModel, self).__init__(*args, **kwargs)
  File "../../keras_bert_ner/utils/models.py", line 75, in __init__
    self._build_bert_model()
  File "../../keras_bert_ner/utils/models.py", line 83, in _build_bert_model
    albert=self.albert)
  File "../../keras_bert_ner/utils/bert.py", line 730, in build_bert_model
    bert.load_weights_from_checkpoint(checkpoint_path)
  File "../../keras_bert_ner/utils/bert.py", line 610, in load_weights_from_checkpoint
    loader("bert/encoder/%s/attention/output/dense/bias" % layer_name)])
  File "/home/nlp/luotong/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 1190, in set_weights
    str(weights)[:50] + '...')
ValueError: You called `set_weights(weights)` on layer "Encoder-1-MultiHeadSelfAttention" with a  weight list of length 8, but the layer was expecting 0 weights. Provided weights: [array([[ 1.1491621e-01,  6.5357164e-03,  1.346404...
请问知道是什么原因吗？

**Comment by bearbro** [comment]
我也遇到了这个问题

**Comment by liushaoweihua** [comment]
之前代码是根据brightmart早期的albert_tiny写的，之前的版本模型早于google放出的albert版本，故而存在模型结构和参数上的不一致。后续brightmart的albert_zh已经根据google版本进行了调整，本项目暂时还没有调整。

后续该模块会集成到 https://github.com/CLUEbenchmark/PyCLUE 的NER模块，当前版本暂时可能没有太多时间调整。或者可以尝试 https://github.com/brightmart/albert_zh 中不带有google字样的albert模型。

非常抱歉。

**Comment by hdchao1989** [comment]
keras版本的问题
